name: AudioPipe Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: master
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov edge-tts
      
      - name: Create test directories
        run: |
          mkdir -p output
      
      - name: Debug token availability
        run: |
          if [ -n "${{ secrets.HUGGING_FACE_TOKEN }}" ]; then
            echo "Hugging Face token is available"
          else
            echo "Hugging Face token is NOT available"
          fi
          
      - name: Run tests with Hugging Face token
        env:
          HUGGING_FACE_TOKEN: ${{ secrets.HUGGING_FACE_TOKEN }}
        run: |
          echo "HUGGING_FACE_TOKEN is set: $(if [ -n \"$HUGGING_FACE_TOKEN\" ]; then echo 'yes'; else echo 'no'; fi)"
          python -m pytest test/test_integration.py -v --integration

      - name: Generate coverage report
        if: matrix.python-version == '3.10'
        env:
          HUGGING_FACE_TOKEN: ${{ secrets.HUGGING_FACE_TOKEN }}
        run: |
          python -m pytest test/ --integration --cov=. --cov-report=xml
          
      - name: Upload coverage to Codecov
        if: matrix.python-version == '3.10'
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: false 